apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-gateway
  template:
    metadata:
      labels:
        name: node-gateway
    spec:
      containers:
      - name: node-gateway
        image: issabaddour/issa_api_gateway:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: node-gateway-service
spec:
  type: LoadBalancer
  selector:
    name: node-gateway
  ports:
    - port: 80
      targetPort: 80